spring:
  application:
    name: article-manager-api-test-task
  config:
    import: optional:file:.env[.properties]

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}